apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:3
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: s3,ec2,iam
            - name: EDGE_PORT
              value: "4566"
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: localstack
spec:
  type: ClusterIP
  ports:
    - port: 4566
      targetPort: 4566
  selector:
    app: localstack
